---
- name: destroy builder
  hosts: host1
  become: true

  tasks:
    - name: Ensure packages are NOT present
      apt:
        name: "{{item}}"
        state: absent
      with_items:
        - default-jre
        - maven
        - git

    - name: Check the repo is absent
      file:
        path: /root/boxfuse
        state: absent


- name: destroy the web server
  hosts: host2
  become: true

  tasks:
    - name: Ensure tomcat is stopped
      service:
        name: tomcat9.service
        state: stopped

    - name: Check webapps is absent
      file:
        path: /var/lib/tomcat9/webapps
        state: absent

    - name: Ensure tomcat package is NOT present
      apt:
        name: tomcat9
        state: absent
