---
# tasks file for builder
- name: Ensure packages are present
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - default-jre
    - maven
    - git

- name: Clone a github repository boxfuse
  git:
    repo: "{{remote_repo}}"
    dest: "{{repo_dir}}"
    clone: true
    update: true
  notify:
    - clean maven
    - build artifact
    - fetch file
    - backup artifact

- name: Check the artifact exists
  stat:
    path: "{{repo_dir}}/{{target_file}}"
  notify:
    - clean maven
    - build artifact
    - fetch file
    - backup artifact
