---
# tasks file for builder
- name: Ensure packages are present
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - default-jre
    - maven
    - git

- name: Clone a github repository boxfuse
  git:
    repo: "{{remote_repo}}"
    dest: "{{repo_dir}}"
    clone: true
    update: true
  notify: "build it"

- name: Check the artifact exists
  stat:
    path: "{{target_file}}"
  register: artifact_file
  changed_when: not artifact_file.stat.exists
  notify: "build it"
