---
# handlers file for builder
- name: clean maven
  shell:
    chdir: "{{repo_dir}}"
    cmd: mvn clean

- name: build artifact
  shell:
    chdir: "{{repo_dir}}"
    cmd: mvn package

- name: fetch file
  synchronize:
    mode: pull
    src: "{{target_file}}"
    dest: "{{archive_file}}"

- name: backup artifact
  synchronize:
    src: "{{archive_file}}"
    dest: "{{archive_dir}}/{{ansible_date_time.iso8601_basic_short}}.war"
  delegate_to: localhost
