---
# handlers file for builder
- name: Clean maven project directory
  shell:
    chdir: "{{repo_dir}}"
    cmd: mvn clean
  listen: "build it"

- name: Build an artifact by maven
  shell:
    chdir: "{{repo_dir}}"
    cmd: mvn package
  listen: "build it"

- name: Fetch the artifact file to the local machine
  synchronize:
    mode: pull
    src: "{{target_file}}"
    dest: "{{archive_file}}"
  listen: "build it"

- name: Backup the artifact on the local machine
  synchronize:
    src: "{{archive_file}}"
    dest: "{{archive_dir}}/{{ansible_date_time.iso8601_basic_short}}.war"
  delegate_to: localhost
  listen: "build it"
